spring:
  datasource:
    url: jdbc:h2:mem:student
    username: root
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none