DROP TABLE IF EXISTS student;
CREATE TABLE `student`(
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `address` VARCHAR(250) DEFAULT NULL,
  `age` INT(1) DEFAULT '0',
  PRIMARY KEY (`id`)
);